name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Verify token presence
        run: |
          if [ -z "${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_RED_MEADOW_082999F10 }}" ]; then
            echo "❌ TOKEN IS EMPTY"
            exit 1
          else
            echo "✅ TOKEN IS PRESENT"
          fi

      - name: Build and Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_RED_MEADOW_082999F10 }}
          action: upload
          app_location: "CharacterNexus/ClientApp"
          output_location: "build"
          api_location: "CharacterNexus"
          app_build_command: "npm install && npm run build"
