name: Build & Deploy CharacterNexus

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy_character_nexus:
    runs-on: ubuntu-latest
    name: Build & Deploy CharacterNexus
    permissions:
      id-token: write
      contents: read
    steps:
      # 1️⃣ Checkout repo
      - uses: actions/checkout@v3
        with:
          submodules: true

      # 2️⃣ Setup .NET SDK
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      # 3️⃣ Restore and build CharacterNexus API
      - name: Restore & Build .NET API
        working-directory: ./CharacterNexus
        run: |
          dotnet restore
          dotnet publish -c Release -o ./publish

      # 4️⃣ Setup Node.js for React
      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install OIDC Client from Core Package
        run: npm install @actions/core@1.6.0 @actions/http-client

      - name: Get Id Token
        uses: actions/github-script@v6
        id: idtoken
        with:
           script: |
               const coredemo = require('@actions/core')
               return await coredemo.getIDToken()
           result-encoding: string

      # 5️⃣ Install React dependencies
      - name: Install React dependencies
        working-directory: ./CharacterNexus/ClientApp
        run: npm install

      # 6️⃣ Build React App
      - name: Build React App
        working-directory: ./CharacterNexus/ClientApp
        run: npm run build

      # 7️⃣ Deploy React app to Azure Static Web Apps
      - name: Deploy React App to SWA
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_AGREEABLE_CLIFF_002808F10 }}
          action: "upload"
          app_location: "CharacterNexus/ClientApp"
          output_location: "build"
          skip_api_build: true
          github_id_token: ${{ steps.idtoken.outputs.result }}

      # 8️⃣ Deploy .NET API to Azure App Service
      - name: Deploy .NET API to App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: "Character-Nexus-API"       # Name of your App Service
          slot-name: "production"             # Default slot
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }} # XML publish profile
          package: ./CharacterNexus/publish
